/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    movies: Movie;
    people: Person;
    'movie-collections': MovieCollection;
    genres: Genre;
    'history-logs': HistoryLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'movie-collections': {
      movies: 'movies';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    movies: MoviesSelect<false> | MoviesSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    'movie-collections': MovieCollectionsSelect<false> | MovieCollectionsSelect<true>;
    genres: GenresSelect<false> | GenresSelect<true>;
    'history-logs': HistoryLogsSelect<false> | HistoryLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'editor')[];
  /**
   * Films the user wishes to archive/watch later.
   */
  watchlist?: (number | Movie)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "movies".
 */
export interface Movie {
  id: number;
  title: string;
  slug: string;
  tmdbId: number;
  tmdbOriginalTitle?: string | null;
  originalLanguage?: string | null;
  overview?: string | null;
  tagline?: string | null;
  releaseDate?: string | null;
  status: 'draft' | 'published';
  adult?: boolean | null;
  video?: boolean | null;
  runtime?: number | null;
  voteAverage?: number | null;
  voteCount?: number | null;
  popularity?: number | null;
  genres?: (number | Genre)[] | null;
  /**
   * Linked series (e.g. Hobbit, LOTR, Spider-man sets).
   */
  collection?: (number | null) | MovieCollection;
  productionCompanies?:
    | {
        tmdbCompanyId?: number | null;
        name: string;
        originCountry?: string | null;
        logoUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  productionCountries?:
    | {
        iso31661?: string | null;
        name: string;
        id?: string | null;
      }[]
    | null;
  spokenLanguages?:
    | {
        englishName?: string | null;
        iso6391?: string | null;
        name: string;
        id?: string | null;
      }[]
    | null;
  directors?: (number | Person)[] | null;
  cast?:
    | {
        person: number | Person;
        character?: string | null;
        id?: string | null;
      }[]
    | null;
  budgets?: {
    budget?: number | null;
    revenue?: number | null;
  };
  /**
   * TMDB veya baska CDN uzerindeki backdrop linki.
   */
  backdropUrl?: string | null;
  /**
   * TMDB poster linki. Dosya projeye yuklenmez.
   */
  posterUrl?: string | null;
  /**
   * Senin hazirladigin posterin Supabase Storage veya harici CDN linki.
   */
  customPosterUrl?: string | null;
  /**
   * Istege bagli custom backdrop linki.
   */
  customBackdropUrl?: string | null;
  customAssetMeta?: {
    posterSource?: string | null;
    posterImportedAt?: string | null;
    posterImportBatch?: string | null;
  };
  /**
   * Tum medya alanlari sadece URL olarak tutulur.
   */
  externalAssets?:
    | {
        label: string;
        kind: 'poster' | 'backdrop' | 'logo' | 'gallery' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  sourceLinks?: {
    tmdb?: string | null;
    imdb?: string | null;
    homepage?: string | null;
  };
  tmdbRaw?: {
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    alternativeTitles?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    credits?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    externalIds?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    images?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    keywords?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    lists?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    recommendations?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    releaseDates?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    reviews?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    similar?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    translations?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    videos?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    watchProviders?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    changes?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  syncMeta?: {
    lastTmdbSyncAt?: string | null;
    lastImportBatch?: string | null;
    sourceLists?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    lastSyncStatus?: string | null;
    tmdbPayloadHash?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres".
 */
export interface Genre {
  id: number;
  name: string;
  slug: string;
  tmdbGenreId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "movie-collections".
 */
export interface MovieCollection {
  id: number;
  name: string;
  slug: string;
  tmdbCollectionId?: number | null;
  overview?: string | null;
  posterUrl?: string | null;
  backdropUrl?: string | null;
  movies?: {
    docs?: (number | Movie)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  slug: string;
  tmdbId?: number | null;
  knownForDepartment?: string | null;
  biography?: string | null;
  /**
   * TMDB profile image link.
   */
  profileUrl?: string | null;
  birthDate?: string | null;
  deathDate?: string | null;
  placeOfBirth?: string | null;
  externalIds?: {
    imdb?: string | null;
    tmdb?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "history-logs".
 */
export interface HistoryLog {
  id: number;
  user: number | User;
  movie: number | Movie;
  watchedAt: string;
  /**
   * Rating out of 10
   */
  rating?: number | null;
  review?: string | null;
  isRewatch?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'movies';
        value: number | Movie;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'movie-collections';
        value: number | MovieCollection;
      } | null)
    | ({
        relationTo: 'genres';
        value: number | Genre;
      } | null)
    | ({
        relationTo: 'history-logs';
        value: number | HistoryLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  watchlist?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "movies_select".
 */
export interface MoviesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tmdbId?: T;
  tmdbOriginalTitle?: T;
  originalLanguage?: T;
  overview?: T;
  tagline?: T;
  releaseDate?: T;
  status?: T;
  adult?: T;
  video?: T;
  runtime?: T;
  voteAverage?: T;
  voteCount?: T;
  popularity?: T;
  genres?: T;
  collection?: T;
  productionCompanies?:
    | T
    | {
        tmdbCompanyId?: T;
        name?: T;
        originCountry?: T;
        logoUrl?: T;
        id?: T;
      };
  productionCountries?:
    | T
    | {
        iso31661?: T;
        name?: T;
        id?: T;
      };
  spokenLanguages?:
    | T
    | {
        englishName?: T;
        iso6391?: T;
        name?: T;
        id?: T;
      };
  directors?: T;
  cast?:
    | T
    | {
        person?: T;
        character?: T;
        id?: T;
      };
  budgets?:
    | T
    | {
        budget?: T;
        revenue?: T;
      };
  backdropUrl?: T;
  posterUrl?: T;
  customPosterUrl?: T;
  customBackdropUrl?: T;
  customAssetMeta?:
    | T
    | {
        posterSource?: T;
        posterImportedAt?: T;
        posterImportBatch?: T;
      };
  externalAssets?:
    | T
    | {
        label?: T;
        kind?: T;
        url?: T;
        id?: T;
      };
  sourceLinks?:
    | T
    | {
        tmdb?: T;
        imdb?: T;
        homepage?: T;
      };
  tmdbRaw?:
    | T
    | {
        details?: T;
        alternativeTitles?: T;
        credits?: T;
        externalIds?: T;
        images?: T;
        keywords?: T;
        lists?: T;
        recommendations?: T;
        releaseDates?: T;
        reviews?: T;
        similar?: T;
        translations?: T;
        videos?: T;
        watchProviders?: T;
        changes?: T;
      };
  syncMeta?:
    | T
    | {
        lastTmdbSyncAt?: T;
        lastImportBatch?: T;
        sourceLists?: T;
        lastSyncStatus?: T;
        tmdbPayloadHash?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tmdbId?: T;
  knownForDepartment?: T;
  biography?: T;
  profileUrl?: T;
  birthDate?: T;
  deathDate?: T;
  placeOfBirth?: T;
  externalIds?:
    | T
    | {
        imdb?: T;
        tmdb?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "movie-collections_select".
 */
export interface MovieCollectionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tmdbCollectionId?: T;
  overview?: T;
  posterUrl?: T;
  backdropUrl?: T;
  movies?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres_select".
 */
export interface GenresSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tmdbGenreId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "history-logs_select".
 */
export interface HistoryLogsSelect<T extends boolean = true> {
  user?: T;
  movie?: T;
  watchedAt?: T;
  rating?: T;
  review?: T;
  isRewatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}